#!/bin/sh
# Script to cleanup leftover loopdevices from mountextfs.
# The script keeps running until there are no mounted loops
# with a mountpoint on /media/removable.

# Turn on/off verbose debugging by uncomment/comment
#set -x
#exec 2>/var/log/unmountloop.log

mountextfs_tmp="/tmp/mount-extfs/"
# Start checking /proc/mounts
while [ "x`cat /proc/mounts|grep /dev/loop )`" != "x" -a \
  "x`cat /proc/mounts|grep /media/removable )`" != "x" ];do 
  cat /proc/mounts|grep /dev/loop|grep -v \
    "/run/crouton/mnt/stateful_partition"| \
    sed 's/ /\;/g'| \
  while read -r line;do
    # echo will replace \040 with space, that is
    # why we replaced it with ; so we can use that 
    # as a delimiter.
    mountpoint=`echo "$line"|cut -d ";" -f 2`
    loopdevice=`echo "$line"|cut -d ";" -f 1`
    mountpoint_1=`echo $mountpoint|sed 's/ /\\\\\\\040/g'`
    # check if our ext2/3/4 device is still mounted
    if [ "x`cat /proc/mounts|grep -v $loopdevice| \
        cut -d " " -f 2|grep -E "^$mountpoint_1$"`" = "x" \
        -a ! -f "$mountextfs_tmp"sd? ];then
      # Unmount the loopdevice and free it
      umount -d "$loopdevice" #"$mountpoint"
      #losetup -d $loopdevice
      # Be sure the directory is empty before deleting. 
      if [ "x`ls -A "$mountpoint"`" = "x" ];then
        rm -r "$mountpoint"
      fi
    fi
  done
  # check every second. 
  sleep 1
done

exit 0
