#!/bin/sh
# Script to cleanup leftover loopdevices from mountextfs.
# The script keeps running until there are no mounted loops
# with a mountpoint on /media/removable.

# Turn on/off verbose debugging by uncomment/comment
#set -x
#exec 2>/var/log/unmountloop.log

mountextfs_tmp="/tmp/mount-extfs/"
# Start checking /proc/mounts
while [ "x`cat /proc/mounts|grep /dev/loop )`" != "x" -a \
  "x`cat /proc/mounts|grep /media/removable )`" != "x" ];do 
  cat /proc/mounts|grep /dev/loop|grep -v \
    "/run/crouton/mnt/stateful_partition"| \
    sed 's/ /\;/g'| \
  while read -r line;do
    # echo will replace \040 with space, that is
    # why we replaced it with ; so we can use that 
    # as a delimiter.
    mountpoint=`echo "$line"|cut -d ";" -f 2`
    loopdevice=`echo "$line"|cut -d ";" -f 1` 
    # check if our ext2/3/4 device is still mounted
    device=`cat /proc/mounts|grep "$mountpoint"|grep -v $loopdevice`
    if [ "x$device" = "x" -a ! -f "$mountextfs_tmp"sd? ];then
      # Unmount the loopdevice and free it
      umount "$mountpoint"
      losetup -d $loopdevice
      # Be sure the directory is empty before deleting. 
      if [ "x`ls -A "$mountpoint"`" = "x" ];then
        rm -r $mountpoint
      fi
    fi
  done
  # check every second. 
  sleep 1
done

exit 0
