#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m | sed -e 's i.86 i386 ;s x86_64 amd64 ;s arm.* armhf ;'`"
fi

if [ -z "$MIRROR" ]; then
    case "$ARCH" in

        i386)   MIRROR="${CROUTON_MIRROR_fedora_i386:-http://fedora.mirror.nexicom.net/linux/releases/20/Fedora/i386/os}"
                ;;
        amd64)   MIRROR="${CROUTON_MIRROR_fedora_x86_64:-http://fedora.mirror.nexicom.net/linux/releases/20/Fedora/x86_64/os}"
                ;;
        armhf)   MIRROR="${CROUTON_MIRROR_fedora_armhf:-http://fedora.mirror.nexicom.net/linux/releases/20/Fedora/armhfp/os}"
                ;;
    esac
fi



