#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the GNOME desktop environment. (Approx. 400MB)'
HOSTBIN='startgnome'
CHROOTBIN='startgnome gnome-session-wrapper'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install --minimal evolution-data-server,fedora=@gnome-desktop gnome-control-center,fedora= \
        gnome-screensaver,fedora= gnome-session,fedora= gnome-session-fallback,fedora= \
        gnome-shell,fedora= gnome-themes-standard,fedora= gvfs-backends,fedora= nautilus,fedora= \
        unzip,fedora=
        
if [ "${DISTROAKA:-"$DISTRO"}" = 'fedora' ]; then
    #Show logout button on gnome3 when there is only one user.
    dconf write /org/gnome/shell/always-show-log-out true
fi

TIPS="$TIPS
You can start GNOME via the startgnome host command: sudo startgnome
"
